# Generated by Django 5.1.4 on 2024-12-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplique_ja', '0002_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
