# Generated by Django 5.1.4 on 2024-12-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplique_ja', '0003_produto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='colorido',
            field=models.TextField(null=True),
        ),
    ]
