# Generated by Django 5.1.4 on 2024-12-15 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplique_ja', '0004_produto_colorido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='colorido',
        ),
    ]
