# Generated by Django 5.1.4 on 2024-12-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplique_ja', '0005_remove_produto_colorido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='date',
            new_name='data',
        ),
    ]
